### ISSUE TITLE
json文件存在，但仍会报错

### ISSUE THREAD

**Issue by shadow1ng** [z2p/sweetPotato#5]
![image](https://user-images.githubusercontent.com/39651966/204228288-01c4e54f-475b-4a25-9424-f568e8cd6dcd.png)

把finger.json内容替换成 {}后，能正常运行

**Comment by shadow1ng** [comment]
用二分法找到报错点，发现这行解析失败        
        "id=\"TypeProdcutName\" value=\"孚盟云\" />",
![image](https://user-images.githubusercontent.com/39651966/204230347-03d862f3-c17b-4ef8-bdb1-d4e50039f038.png)
![image](https://user-images.githubusercontent.com/39651966/204230431-f82dbae5-6faf-465d-a831-36934ec39acd.png)

**Comment by shadow1ng** [comment]
删除改行后，发现还会有报错。可能不止一处。
![image](https://user-images.githubusercontent.com/39651966/204231233-61db460a-0cfe-4901-8061-ef8c42933f67.png)
不确定是否和java版本有关
![image](https://user-images.githubusercontent.com/39651966/204231118-865604c6-77c3-4c2e-b84e-07b47c24156a.png)

**Comment by z2p** [comment]
json配置文件的错误，我看一下；jdk你可以试试别的，不要用openjdk试试？

我的java环境是：
java 14.0.2 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

**Comment by shadow1ng** [comment]
后面试了下java19 jdk，能正常运行
