### ISSUE TITLE
建议新增微信UA

### ISSUE THREAD

**Issue by Evi10x01** [z2p/sweetPotato#6]
平时有些目标是必须要微信客户端访问，建议UA修改这块新增一个微信客户端的UA或者UA可自定义修改。

**Comment by z2p** [comment]
<img width="601" alt="image" src="https://user-images.githubusercontent.com/25349590/205426034-8d2d91ae-ddf6-40aa-8f9f-94b9a972f215.png">
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/25349590/205426042-d3d9df62-f340-4a52-be28-3396f689fd7e.png">

目前可以通过自定义头部字段的功能解决这类问题，当然如果你有识别到哪些是微信UA和对这类有判断的网站发给我，我可以看一下是否能解决并将其加入到功能当中
